# Generated by Django 5.2.6 on 2025-09-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subscribers_subscribed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='subscribed_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date subscibed'),
        ),
    ]
