# Generated by Django 5.2.6 on 2025-09-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='subscribed_on',
            field=models.DateTimeField(null=True, verbose_name='date subscibed'),
        ),
    ]
